---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liukai.
--- DateTime: 2018/9/7 下午5:10
---



--获得zoneId的值
local zoneId = ngx.req.get_headers()["zoneId"]


--根据zoneId的值进行路由
if zoneId == "wd" then

    --通过 capture 进行内部转发
    local wd = ngx.location.capture("/wd")

    ngx.say(wd.body)

else

    local ty = ngx.location.capture("/ty")

    ngx.say(ty.body)

end